name: Pull Request CI

on:
  pull_request:

jobs:
  pull-request-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Steps for the Client Folder
      - name: Install Dependencies (Client)
        run: |
          cd client
          pnpm install --frozen-lockfile

      - name: Run TypeScript Compiler (Client)
        run: |
          cd client
          pnpm tsc

      - name: Run Linter (Client)
        run: |
          cd client
          pnpm lint

      #   - name: Run Tests (Client)
      #     run: |
      #       cd client
      #       pnpm test

      # Steps for the Server Folder
      - name: Install Dependencies (Server)
        run: |
          cd server
          pnpm install --frozen-lockfile

      - name: Run TypeScript Compiler (Server)
        run: |
          cd server
          pnpm tsc

    #   - name: Run Linter (Server)
    #     run: |
    #       cd server
    #       pnpm lint

    #   - name: Run Tests (Server)
    #     run: |
    #       cd server
    #       pnpm test
